name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-ci-cd-demo:${{ github.run_number }} .

      - name: Log in to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-ci-cd-demo:${{ github.run_number }}

  deploy:
    needs: build-test-deploy
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set KUBECONFIG
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      - name: Replace image tag with run number
        run: sed -i '' "s/__VERSION__/${{ github.run_number }}/g" k8s/deployment.yaml
        
      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/
